name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target x86_64-pc-windows-gnu

      - uses: actions/upload-artifact@v3
        with:
          name: orgb.exe
          path: target/**/orgb.exe
