name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build the binary
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          use-cross: true
          command: cargo build
          args: --release --target x86_64-pc-windows-gnu

      - name: Upload the binary
        uses: actions/upload-artifact@v3
        with:
          name: orgb
          path: target/x86_64-pc-windows-gnu/release/orgb.exe
